name: Build Test Container

on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  package:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main
